# Generated by Django 4.2.4 on 2023-08-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.IntegerField(choices=[(0, 'Immobilien anbieten'), (1, 'Immobilien'), (2, 'Bau'), (3, 'Finanzierung'), (4, 'Projektentwicklung'), (5, 'Consulting'), (6, 'Tippgeber werden bei der Tumuratas Group'), (7, 'Karriere'), (8, 'Suchauftrag für Immobilien und Projekte'), (9, 'Sonstiges')], default=0, verbose_name='Anliegen')),
                ('firstname', models.CharField(max_length=100, verbose_name='Vorname*')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nachname*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('tel', models.CharField(blank=True, max_length=26, null=True, verbose_name='Telefonnummer*')),
                ('street', models.CharField(blank=True, max_length=80, null=True, verbose_name='Straße')),
                ('postialcode', models.CharField(blank=True, max_length=80, null=True, verbose_name='Postleizahl')),
                ('city', models.CharField(blank=True, max_length=80, null=True, verbose_name='Stadt')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('inquiry_send_at_date', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('checked', models.BooleanField(default=False, verbose_name='Bearbeitet?')),
            ],
        ),
    ]
