# Generated by Django 4.2.4 on 2023-08-15 23:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gewerblich', models.BooleanField(default=False)),
                ('property_title', models.CharField(max_length=220, verbose_name='Titel der Immobilie')),
                ('plan', models.CharField(choices=[('Verkaufen', 'Kaufen'), ('Vermieten', 'Mieten')], default='Verkaufen', max_length=30)),
                ('street', models.CharField(max_length=120, verbose_name='Straße')),
                ('housenumber', models.CharField(max_length=70, verbose_name='Hausnummer')),
                ('postialcode', models.CharField(max_length=70, verbose_name='Postleihzahl')),
                ('city', models.CharField(max_length=120, verbose_name='Stadt')),
                ('country', models.CharField(choices=[('Deutschland', 'Deutschland'), ('Türkei', 'Türkei')], default='Deutschland', max_length=220, verbose_name='Land')),
                ('title_picture', models.ImageField(upload_to='fotos/immo')),
                ('total_area', models.CharField(max_length=60, verbose_name='Gesamtfläche')),
                ('price', models.IntegerField(verbose_name='Preis der Immobilie')),
                ('object_type', models.CharField(choices=[('Grundstück', 'Grundstück'), ('Einfamilienhaus/Rheinhaus', 'Einfamilienhaus/Rheinhaus'), ('Mehrfamilienhaus', 'Mehrfamilienhaus'), ('Gewerbeobjekt', 'Gewerbeobjekt'), ('Gewerbegrundstück', 'Gewerbegrundstück'), ('Kapitalanlage', 'Kapitalanlage'), ('Neubau', 'Neubau'), ('Lagerhallen', 'Lagerhallen')], max_length=60, verbose_name='Objekttyp')),
                ('area_to_live', models.CharField(blank=True, max_length=60, null=True, verbose_name='Wohnfläche')),
                ('total_ground_size', models.CharField(blank=True, max_length=60, null=True, verbose_name='Grundstückgröße')),
                ('area_of_use', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nutzfläche')),
                ('amount_of_bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Anzahl Schlafzimmer')),
                ('amount_of_rooms', models.IntegerField(blank=True, null=True, verbose_name='Anzahl Zimmer')),
                ('amount_of_bathrooms', models.IntegerField(blank=True, null=True, verbose_name='Anzahl Badezimmer')),
                ('available_date', models.DateField(blank=True, null=True, verbose_name='Bezugsfrei ab')),
                ('build_in_year', models.CharField(blank=True, max_length=7, null=True, verbose_name='Baujahr')),
                ('energypass_available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Energypass vorhanden')),
                ('energypass_type', models.CharField(blank=True, max_length=40, null=True)),
                ('object_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Objektbeschreibung')),
                ('equipment_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Beschreibung der Ausstattung')),
                ('location_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Lagebeschreibung')),
                ('other_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sonstige Beschreibung')),
                ('has_keller', models.BooleanField(blank=True, default=False, null=True, verbose_name='Keller vorhanden?')),
                ('has_balkon', models.BooleanField(blank=True, default=False, null=True, verbose_name='Balkon vorhanden?')),
                ('has_garage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Garage/Abstellplatz vorhanden?')),
                ('is_for_selling', models.BooleanField(default=True, verbose_name='Ist Objekt zu verkaufen?')),
                ('is_for_renting', models.BooleanField(default=False, verbose_name='Ist Objekt zu vermieten?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Wurde hinzugefügt am')),
                ('is_available', models.BooleanField(default=True, verbose_name='Ist Objekt verfügbar?')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Vorname*')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nachname*')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('tel', models.CharField(help_text='Gib deine Telefonnummer hier ein.', max_length=50, verbose_name='Telefonnummer*')),
                ('objecttype', models.CharField(choices=[('Grundstück', 'Grundstück'), ('Einfamilienhaus', 'Einfamilienhaus'), ('Mehrfamilienhaus', 'Mehrfamilienhaus'), ('Gewerbeobjekt', 'Gewerbeobjekt'), ('Anlageobjekt', 'Anlageobjekt'), ('Wohnung', 'Wohnung'), ('Lagerhallen', 'Lagerhallen'), ('Neubau', 'Neubau'), ('Kapitalanlage', 'Kapitalanlage')], max_length=50, verbose_name='Objektart*')),
                ('market_plan', models.CharField(blank=True, choices=[('Verkauf', 'Zum Verkauf'), ('Vermieten', 'Zum Vermieten')], default='Verkauf', max_length=50, null=True, verbose_name='Objektvorhaben*')),
                ('total_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Wohnfläche in qm')),
                ('living_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nutzfläche in qm')),
                ('ground_size', models.CharField(blank=True, max_length=30, null=True, verbose_name='Grundstückgröße in qm')),
                ('building_year', models.CharField(max_length=30, verbose_name='Baujahr')),
                ('street', models.CharField(max_length=90, verbose_name='Straße*')),
                ('housenumber', models.CharField(max_length=50, verbose_name='Hausnummer*')),
                ('postialcode', models.CharField(max_length=50, verbose_name='Postleizahl*')),
                ('city', models.CharField(max_length=90, verbose_name='Stadt*')),
                ('country', models.CharField(choices=[('Deutschland', 'Deutschland'), ('Türkei', 'Türkei')], default='Deutschland', max_length=70, verbose_name='Land')),
                ('notification', models.TextField(blank=True, null=True, verbose_name='Sonstiges')),
            ],
            options={
                'verbose_name': 'Neue Immobilieangebot',
                'verbose_name_plural': 'Neue Immobilienangebote',
                'db_table': 'neue_immobilien_angebote',
            },
        ),
        migrations.CreateModel(
            name='SearchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=60, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='Email*')),
                ('tel', models.CharField(max_length=60, verbose_name='Telefon')),
                ('search_for_objecttype', models.CharField(choices=[('Grundstück', 'Grundstück'), ('Einfamilienhaus', 'Einfamilienhaus'), ('Doppelhauskälfte', 'Doppelhauskälfte'), ('Gewerbegrundstück', 'Gewerbegrundstück'), ('Gewerblich', 'Gewerblich'), ('Wohnung', 'Wohnung')], max_length=70, verbose_name='Objekttyp')),
                ('searched_city', models.CharField(max_length=60, verbose_name='Stadt')),
                ('searched_postialcode', models.CharField(max_length=60, verbose_name='Postleizahl')),
                ('distance', models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90')], default=(10, '10'), verbose_name='Distanzraum in Km')),
            ],
        ),
        migrations.CreateModel(
            name='Property_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotos/immo')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPropertyInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=80, verbose_name='Nachname')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('tel', models.CharField(blank=True, max_length=80, null=True, verbose_name='Telefonnummer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Immobilie')),
            ],
            options={
                'db_table': 'immobilien_anfragen',
            },
        ),
    ]
